apiVersion: v1
kind: Service
metadata:
  name: random-service
  namespace: example
  labels:
    model: s2s
spec:
  selector:
    name: s1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
